export const listablePageList = [
  {
    id: "1",
    title: "Page 1",
    ownerId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    parentId: null,
  },
  {
    id: "2",
    title: "Page 2",
    ownerId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    parentId: "1",
  },
  {
    id: "3",
    title: "Page 3",
    ownerId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    parentId: "1",
  },
  {
    id: "4",
    title: "Page 4",
    ownerId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    parentId: "2",
  },
  {
    id: "5",
    title: "Page 5",
    ownerId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    parentId: "3",
  },
  {
    id: "6",
    title: "Page 6",
    ownerId: "user1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    parentId: null,
  },
];
